# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.danielcirket.co.uk" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Dan Cirket
  avatar: https://avatars3.githubusercontent.com/u/6743309?v=3&s=96
  gravatar: # Email MD5 hash
  description: "Software and Web Developer" # used by search engines

  # Header and footer text
  header_text: 
  header_text_feature_image:
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a>

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: danielcirket
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: DanCirket
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-46527412-1 
  disqus_shortname:
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

permalink: /:title/ 

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]